### ISSUE TITLE
3.3 As a user, I want to be able to add friends so that I can interact with them. [5]

### ISSUE THREAD

**Issue by ksutjipt** [CSE115-project/nextjs-ff#34]
i) Create button to add friends

ii) Link friends to database

**Comment by huy-nguy3n** [comment]
Huy will finish, adding tab bar and friend list

**Comment by kainoabrabo** [comment]
1. Can add friends to personal list.  Friends won't automatically add user because we are using a "follower" design rather than mutual friends with a request.
