### ISSUE TITLE
3.1 As a user, I want to see hotspots for attractions so I know where to go. [3]

### ISSUE THREAD

**Issue by ksutjipt** [CSE115-project/nextjs-ff#36]
i) Add hotspot feature from Google Maps 			
ii) Use certain attractions to limit the scope of hot spots

**Comment by huy-nguy3n** [comment]
add places library 
set up basis for heatmap

**Comment by kainoabrabo** [comment]
Got heatmap to display under markers.  Will continue to refine the heat map in sprint 4
