### ISSUE TITLE
Marker for location

### ISSUE THREAD

**Issue by huy-nguy3n** [CSE115-project/nextjs-ff#52]
- On click, display a pop up with location information (name, address, phone number and ratings)
- Add to like places button 
- change marker for place to signal chosen place

**Comment by kainoabrabo** [comment]
https://mui.com/joy-ui/react-tooltip/

**Comment by kainoabrabo** [comment]
update color and size of places marker

**Comment by kainoabrabo** [comment]
add marker info window on click

**Comment by kainoabrabo** [comment]
deleted the infowindow and implemented an infocard, also added a panTo function to center the place marker clicked

**Comment by kainoabrabo** [comment]
finished like button functionality, works with add and remove from DB
