### ISSUE TITLE
Add search input to change current location

### ISSUE THREAD

**Issue by huy-nguy3n** [CSE115-project/nextjs-ff#54]

**Comment by huy-nguy3n** [comment]
add search input to the middle of the nav bar

**Comment by kainoabrabo** [comment]
Add "Search This Area" button when dragging map. Only heat map displays right now.

todo: Repopulate markers on "Search..."

**Comment by kainoabrabo** [comment]
1. Drag to a new location, "Search Area" button appears on drag-end.
2. onClick "Search Area" for 60 new places, then button disappears
